#!/bin/sh
### BEGIN INIT INFO
# Provides:          Back-end
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Should-Start:      hunter-gatherer
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: backend daemon service for AutoGrab
# Description:       Backend service for the AutoGrab application. Scrapes and machine learns about car data.
### END INIT INFO

USER=autograb-backend
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="autograb-backend"
DAEMON=/usr/local/bin/$NAME
DAEMON_OPTS=$2
DESC="Backend service for the AutoGrab application"
PIDFILE="/var/run/puppet/${NAME}.pid"

reload_autograb_backend() {
        start-stop-daemon --stop --quiet --signal HUP --pidfile $PIDFILE
}

start_autograb_backend() {
    start-stop-daemon --start --quiet --background --pidfile $PIDFILE \
        --startas $DAEMON $DAEMON_OPTS
}

stop_autograb_backend() {
        start-stop-daemon --stop --retry TERM/10/KILL/5 --quiet --oknodo --pidfile $PIDFILE
}

status_autograb_backend() {
        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}"
}

case "$1" in
    start)
        start_autograb_backend
        ;;
    stop)
        stop_autograb_backend
        ;;
    reload)
        reload_autograb_backend
        ;;
    status)
        status_autograb_backend
        ;;
    restart)
        stop_autograb_backend
        start_autograb_backend
        ;;
  *)
        echo "Usage: $0 {start|stop|status|restart|reload}" >&2
        exit 1
        ;;
esac
